
// ********RoostGPT********
/*
Test generated by RoostGPT for test pw-ut-azureai-github-1776663509748 using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=getUserId_86f43cc280
ROOST_METHOD_SIG_HASH=getUserId_3ede2791e1

Scenario 1: Retrieving the user ID after construction with valid input

Details:
  TestName: getUserIdReturnsSetUserIdValue
  Description: This test verifies that the getUserId() method returns the correct user ID that was provided via the parameterized constructor. It checks the basic functionality of the getter with an expected positive user ID value set at construction.
Execution:
  Arrange: Create a ForumChatModel instance using the parameterized constructor, providing a specific integer value (e.g., 123) for userId.
  Act: Call getUserId() on the created instance.
  Assert: Verify that the returned value equals 123.
Validation:
  This assertion ensures that the constructor correctly assigns the userId field, and that getUserId() reliably returns that value. It is fundamental to confirm the getter behaves accurately for typical inputs.


*/

// ********RoostGPT********

package com.medeiros.SPRINGProject.Models;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;
import jakarta.persistence.*;

public class ForumChatModelGetUserIdTest {

	@Test
	@Tag("valid")
	public void testGetUserIdReturnsSetUserIdValue() {
		// Arrange
		ForumChatModel forumChatModel = new ForumChatModel("Sample message", 123, 456); // TODO:
																						// Change
																						// to
																						// desired
																						// values
																						// if
																						// needed
		// Act
		int actualUserId = forumChatModel.getUserId();
		// Assert
		assertEquals((int) 123, (int) actualUserId);
	}

}