
// ********RoostGPT********
/*
Test generated by RoostGPT for test UnitTest-Java using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022

ROOST_METHOD_HASH=getId_582e5a2030
ROOST_METHOD_SIG_HASH=getId_92e05748b6

Scenario 1: Verify Default ID Value

Details:
  TestName: getDefaultIdValue
  Description: Validates that a newly created User_Info instance returns the default ID value (0)

Execution:
  Arrange: Create a new instance of User_Info class
  Act: Call getId() method
  Assert: Verify that the returned ID equals 0

Validation:
  The test ensures that uninitialized ID field returns the default integer value.
  This is important for validating the initial state of User_Info objects.

*/

// ********RoostGPT********

package com.medeiros.SPRINGProject.Models;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Table;

class UserInfoGetIdTest {

	@Test
	@Tag("valid")
	void getDefaultIdValue() {
		// Arrange
		User_Info userInfo = new User_Info();

		// Act
		int actualId = userInfo.getId();

		// Assert
		assertEquals(0, actualId);
	}

	@Test
	@Tag("valid")
	void getCustomIdValue() {
		// Arrange
		User_Info userInfo = new User_Info(1, "photo.jpg", "rock", "male", "123456789", "insta.com", "twitter.com",
				"reading");

		// Act
		int actualId = userInfo.getId();

		// Assert
		assertEquals(1, actualId);
	}

	@Test
	@Tag("boundary")
	void getMaxIdValue() {
		// Arrange
		User_Info userInfo = new User_Info(Integer.MAX_VALUE, "photo.jpg", "rock", "male", "123456789", "insta.com",
				"twitter.com", "reading");

		// Act
		int actualId = userInfo.getId();

		// Assert
		assertEquals(Integer.MAX_VALUE, actualId);
	}

	@Test
	@Tag("boundary")
	void getMinIdValue() {
		// Arrange
		User_Info userInfo = new User_Info(Integer.MIN_VALUE, "photo.jpg", "rock", "male", "123456789", "insta.com",
				"twitter.com", "reading");

		// Act
		int actualId = userInfo.getId();

		// Assert
		assertEquals(Integer.MIN_VALUE, actualId);
	}

}