
// ********RoostGPT********
/*
Test generated by RoostGPT for test pw-ut-claudeai-gitlab-1772707133036 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=loginUser_d19666d97a
ROOST_METHOD_SIG_HASH=loginUser_8fe76c816e


Scenario 1: Valid User Login

Details:
  TestName: testValidUserLogin
  Description: This test is meant to check if a user with valid credentials is able to login successfully.
Execution:
  Arrange: Mock the UserAccRepo to return a User_Credentials object when findUserByEmail is called with a valid email. The User_Credentials object should have the same password as the one used in the test.
  Act: Invoke the loginUser method with the valid email and password.
  Assert: Assert that the return value is "Logado".
Validation:
  The assertion verifies that a user with valid credentials is able to login. This is expected as it is the correct behavior of the application.

Scenario 2: Invalid User Login - Incorrect Password

Details:
  TestName: testInvalidUserLoginIncorrectPassword
  Description: This test is meant to check if a user with an incorrect password is unable to login.
Execution:
  Arrange: Mock the UserAccRepo to return a User_Credentials object when findUserByEmail is called with a valid email. The User_Credentials object should have a different password than the one used in the test.
  Act: Invoke the loginUser method with the valid email and incorrect password.
  Assert: Assert that the return value is "Senha incorreta".
Validation:
  The assertion verifies that a user with an incorrect password is unable to login. This is expected as it is the correct behavior of the application.

Scenario 3: Invalid User Login - Non-existent Email

Details:
  TestName: testInvalidUserLoginNonExistentEmail
  Description: This test is meant to check if a user with a non-existent email is unable to login.
Execution:
  Arrange: Mock the UserAccRepo to return null when findUserByEmail is called with a non-existent email.
  Act: Invoke the loginUser method with the non-existent email and any password.
  Assert: Assert that the return value is "Email não encontrado!".
Validation:
  The assertion verifies that a user with a non-existent email is unable to login. This is expected as it is the correct behavior of the application.

*/

// ********RoostGPT********

package com.medeiros.SPRINGProject.Controllers;

import com.medeiros.SPRINGProject.Models.User_Credentials;
import com.medeiros.SPRINGProject.Models.UserAccRepository;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;
import org.junit.jupiter.api.*;
import com.medeiros.SPRINGProject.Models.*;
import com.medeiros.SPRINGProject.Security.JwtUtil;
import org.springframework.web.bind.annotation.*;
import java.util.Objects;

public class AuthControllerLoginUserTest {

	@Autowired
	private UserAccRepository UserAccRepo;

	@Autowired
	private AuthController authController;

	@Test
	@Tag("valid")
	public void testValidUserLogin() {
		String email = "test@test.com";
		String password = "password";
		User_Credentials user = new User_Credentials(email, password, "username");
		when(UserAccRepo.findUserByEmail(email)).thenReturn(user);
		String result = authController.loginUser(email, password);
		assertEquals("Logado", result);
	}

	@Test
	@Tag("invalid")
	public void testInvalidUserLoginIncorrectPassword() {
		String email = "test@test.com";
		String password = "password";
		User_Credentials user = new User_Credentials(email, "wrongPassword", "username");
		when(UserAccRepo.findUserByEmail(email)).thenReturn(user);
		String result = authController.loginUser(email, password);
		assertEquals("Senha incorreta", result);
	}

	@Test
	@Tag("invalid")
	public void testInvalidUserLoginNonExistentEmail() {
		String email = "nonExistent@test.com";
		String password = "password";
		when(UserAccRepo.findUserByEmail(email)).thenReturn(null);
		String result = authController.loginUser(email, password);
		assertEquals("Email não encontrado!", result);
	}

}