
// ********RoostGPT********
/*
Test generated by RoostGPT for test pw-ut-openai-github-1773725373879 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=newMessage_7d9702b2ce
ROOST_METHOD_SIG_HASH=newMessage_f58e857aa0


  Scenario 1: Test for a valid new message creation

  Details:
    TestName: testValidNewMessageCreation.
    Description: This test is meant to check if a new message is created successfully when valid parameters are passed.
  Execution:
    Arrange: Create a mock for the ChatRepository and set its save method to return the input parameter. Create a valid message, userId and forumId.
    Act: Invoke the newMessage method with the valid message, userId and forumId.
    Assert: Use JUnit assertions to compare the returned message with the input message.
  Validation:
    The assertion aims to verify that the returned message is the same as the input message, which indicates that the message was saved successfully. This test is significant in ensuring that the application can successfully create new messages.

*/

// ********RoostGPT********

package com.medeiros.SPRINGProject.Controllers;

import com.medeiros.SPRINGProject.Models.ForumChatModel;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;
import com.medeiros.SPRINGProject.Models.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@SpringBootTest
public class ForumControllerNewMessageTest {

	@InjectMocks
	private ForumController forumController;

	@Mock
	private ForumChatRepository chatRepository;

	@Test
	@Tag("valid")
	public void testValidNewMessageCreation() {
		// Arrange
		String message = "Test message";
		int userId = 1;
		int forumId = 1;
		ForumChatModel messageForum = new ForumChatModel(message, userId, forumId);
		Mockito.when(chatRepository.save(Mockito.any(ForumChatModel.class))).thenReturn(messageForum);
		// Act
		String result = forumController.newMessage(message, userId, forumId);
		// Assert
		assertEquals(message, result, "The returned message should match the input message");
	}

}