
// ********RoostGPT********
/*
Test generated by RoostGPT for test amanVertexAi2nd using AI Type Vertex AI and AI Model gemini-2.5-pro

ROOST_METHOD_HASH=showAllProducts_e3f486dbbd
ROOST_METHOD_SIG_HASH=showAllProducts_f2f96749da

Scenario 1: Verify the method returns all products when the repository contains multiple items.

Details:
  TestName: showAllProductsReturnsListOfProductsWhenRepositoryIsPopulated
  Description: This test ensures that the `showAllProducts` method correctly retrieves and returns a collection of `ProductModel` objects when the `ProductRepository` has multiple products stored.
Execution:
  Arrange: Create a mock for the `ProductModelRepository`. Prepare a list containing several `ProductModel` instances. Configure the mock so that a call to `ProductRepository.findAll()` returns this pre-defined list of products.
  Act: Invoke the `showAllProducts()` method of the `MarketController`.
  Assert: Assert that the returned `Iterable<ProductModel>` is not null. Verify that the size of the returned iterable matches the size of the list created in the arrange step. Compare the content of the returned iterable to ensure it is identical to the original list of products.
Validation:
  This test validates the primary, or "happy path," functionality of the method. It confirms that the controller correctly communicates with the repository and returns the complete dataset as expected, which is its core responsibility.

Scenario 2: Verify the method returns an empty collection when the repository has no products.

Details:
  TestName: showAllProductsReturnsEmptyListWhenRepositoryIsEmpty
  Description: This test checks the behavior of the `showAllProducts` method when the underlying `ProductRepository` is empty. It should return an empty, non-null collection.
Execution:
  Arrange: Create a mock for the `ProductModelRepository`. Configure the mock so that a call to `ProductRepository.findAll()` returns an empty `ArrayList`.
  Act: Invoke the `showAllProducts()` method of the `MarketController`.
  Assert: Assert that the returned `Iterable<ProductModel>` is not null. Assert that the returned iterable is empty.
Validation:
  This is a critical edge case test. It ensures that the application handles scenarios with no data gracefully, preventing potential `NullPointerExceptions` or other errors in components that might consume this method's output. It confirms the system behaves predictably when the database table is empty.

Scenario 3: Verify the method's behavior when the repository's `findAll` method throws an exception.

Details:
  TestName: showAllProductsPropagatesExceptionWhenRepositoryFails
  Description: This test ensures that if the `ProductRepository.findAll()` method throws a runtime exception (e.g., a `DataAccessException` indicating a database connection issue), the exception is correctly propagated up from the `showAllProducts` method.
Execution:
  Arrange: Create a mock for the `ProductModelRepository`. Configure the mock so that a call to `ProductRepository.findAll()` throws a `RuntimeException` (or a more specific data access exception).
  Act: Call the `showAllProducts()` method within a test construct designed to catch exceptions, such as JUnit 5's `assertThrows`.
  Assert: Assert that the expected `RuntimeException` is thrown when the `showAllProducts()` method is executed.
Validation:
  This scenario is crucial for testing the application's resilience and error handling. It verifies that repository-level failures are not silently suppressed and are correctly passed up the call stack, allowing a higher-level exception handler (like a Spring `@ControllerAdvice`) to manage the error and return an appropriate HTTP status to the client.

*/

// ********RoostGPT********

package com.medeiros.SPRINGProject.Controllers;

import com.medeiros.SPRINGProject.Models.LogRepository;
import com.medeiros.SPRINGProject.Models.ProductModel;
import com.medeiros.SPRINGProject.Models.ProductModelRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.dao.DataAccessResourceFailureException;
import org.junit.jupiter.api.Tag;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.when;
import org.junit.jupiter.api.*;
import com.medeiros.SPRINGProject.Models.LogModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@ExtendWith(MockitoExtension.class)
class MarketControllerShowAllProductsTest {

	@Mock
	private ProductModelRepository ProductRepository;

	@Mock
	private LogRepository Log;

	@InjectMocks
	private MarketController marketController;

	@Test
	@Tag("valid")
	void showAllProductsReturnsListOfProductsWhenRepositoryIsPopulated() {
		// Arrange
		ProductModel product1 = new ProductModel("Laptop", 1200.50, 101, 1, "electronics");
		ProductModel product2 = new ProductModel("Mouse", 25.00, 102, 1, "electronics");
		List<ProductModel> expectedProducts = Arrays.asList(product1, product2);
		when(ProductRepository.findAll()).thenReturn(expectedProducts);
		// Act
		Iterable<ProductModel> actualProductsIterable = marketController.showAllProducts();
		// Assert
		assertNotNull(actualProductsIterable);
		List<ProductModel> actualProducts = StreamSupport.stream(actualProductsIterable.spliterator(), false)
			.collect(Collectors.toList());
		assertEquals(expectedProducts.size(), actualProducts.size());
		assertEquals(expectedProducts, actualProducts);
	}

	@Test
    @Tag("boundary")
    void showAllProductsReturnsEmptyListWhenRepositoryIsEmpty() {
        // Arrange
        when(ProductRepository.findAll()).thenReturn(Collections.emptyList());
        // Act
        Iterable<ProductModel> result = marketController.showAllProducts();
        // Assert
        assertNotNull(result);
        assertFalse(result.iterator().hasNext(), "The returned iterable should be empty.");
    }

	@Test
	@Tag("invalid")
	void showAllProductsPropagatesExceptionWhenRepositoryFails() {
		// Arrange
		String exceptionMessage = "Error connecting to the database";
		when(ProductRepository.findAll()).thenThrow(new DataAccessResourceFailureException(exceptionMessage));
		// Act & Assert
		DataAccessResourceFailureException thrown = assertThrows(DataAccessResourceFailureException.class,
				() -> marketController.showAllProducts(), "Expected showAllProducts to throw, but it didn't");
		assertEquals(exceptionMessage, thrown.getMessage());
	}

}